CREATE TABLE departments (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(50) NOT NULL
);

INSERT INTO departments (department_id, department_name)
VALUES
(1, 'Sales'),
(2, 'Finance'),
(3, 'Marketing'),
(4, 'Operations'),
(5, 'IT');

CREATE TABLE employees (
    employee_id INT PRIMARY KEY,
    employee_name VARCHAR(100) NOT NULL,
    department_id INT,
    salary DECIMAL(10,2),

    FOREIGN KEY (department_id)
    REFERENCES departments(department_id)
);
INSERT INTO employees
(employee_id, employee_name, department_id, salary)
VALUES
(101, 'Rahul', 1, 45000),
(102, 'Priya', 1, 55000),
(103, 'Amit', 1, 40000),
(104, 'Neha', 2, 60000),
(105, 'Karan', 3, 50000),
(106, 'Sneha', 4, 48000),
(107, 'Rohit', 1, 70000),
(108, 'Pooja', 5, 65000);

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50)
);
INSERT INTO customers
(customer_id, customer_name, city)
VALUES
(201, 'ABC Traders', 'Delhi'),
(202, 'XYZ Retail', 'Mumbai'),
(203, 'Kumar Enterprises', 'Delhi'),
(204, 'Sharma Stores', 'Jaipur'),
(205, 'Global Mart', 'Bangalore'),
(206, 'City Electronics', 'Pune'),
(207, 'Prime Retail', 'Delhi'),
(208, 'Star Enterprises', 'Chennai'),
(209, 'Metro Mart', 'Mumbai'),
(210, 'Future Retail', 'Noida');

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2)
);
INSERT INTO products
(product_id, product_name, category, price)
VALUES
(301, 'Laptop', 'Electronics', 60000),
(302, 'Mobile', 'Electronics', 30000),
(303, 'Headphones', 'Electronics', 3000),
(304, 'Office Chair', 'Furniture', 8000),
(305, 'Desk', 'Furniture', 12000),
(306, 'Printer', 'Electronics', 15000),
(307, 'Notebook', 'Stationery', 500),
(308, 'Pen Set', 'Stationery', 300);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    employee_id INT,
    product_id INT,
    order_date DATE,
    quantity INT,
    amount DECIMAL(12,2),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id),

    FOREIGN KEY (employee_id)
    REFERENCES employees(employee_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);

INSERT INTO orders
(order_id, customer_id, employee_id, product_id, order_date, quantity, amount)
VALUES
(1001, 201, 101, 301, '2026-01-05', 2, 120000),
(1002, 202, 102, 302, '2026-01-08', 3, 90000),
(1003, 203, 103, 304, '2026-01-12', 5, 40000),
(1004, 204, 101, 303, '2026-01-15', 10, 30000),
(1005, 205, 107, 301, '2026-01-20', 1, 60000),
(1006, 201, 102, 305, '2026-02-02', 4, 48000),
(1007, 206, 103, 306, '2026-02-05', 2, 30000),
(1008, 207, 107, 302, '2026-02-10', 5, 150000),
(1009, 208, 101, 307, '2026-02-14', 20, 10000),
(1010, 209, 102, 308, '2026-02-18', 30, 9000),
(1011, 210, 107, 301, '2026-03-01', 2, 120000),
(1012, 202, 103, 303, '2026-03-05', 15, 45000),
(1013, 203, 101, 305, '2026-03-10', 3, 36000),
(1014, 201, 107, 306, '2026-03-15', 4, 60000),
(1015, 205, 102, 302, '2026-03-20', 2, 60000);

select * from customers 
select * from departments 
select * from  employees 
select * from  orders 
select * from products 



##Basic & Sales Analysis
--Q1. Find the total revenue generated by the company.
select sum(o.quantity*p.price)as total_revenue
from orders o
join products p
on o.product_id=p.product_id


--Q2. Find the total number of orders placed.
select count(order_id)as total_orders_placed 
from orders 



--Q3. Find the total quantity of products sold.
select sum(quantity)as total_quantity_placed 
from orders 


--Q4. Find the total sales generated by each product.
select p.product_id,p.product_name,sum(o.amount)as sales_generated
from products p 
join orders o
on p.product_id=o.product_id
group by  p.product_id,p.product_name

--Q5. Find the top 5 products based on total revenue.
select p.product_id,p.product_name,sum(o.amount) product_revenue
from products p 
join orders o
on p.product_id=o.product_id
group by  p.product_id,p.product_name
order by product_revenue desc 
limit 5;


##Customer Analysis
--Q6. Find the total amount spent by each customer.
select c.customer_id,c.customer_name,sum(o.amount)as amount_spent
from customers c
join orders o
on c.customer_id=o.customer_id
group by  c.customer_id,c.customer_name
order by  amount_spent desc;


--Q7. Find the top 3 customers based on total spending.
select c.customer_id,c.customer_name,sum(o.amount)as total_spending
from customers c
join orders o
on c.customer_id=o.customer_id
group by  c.customer_id,c.customer_name
order by  total_spending desc
limit 3;


--Q8. Find customers who have placed more than one order.
select c.customer_id,c.customer_name,count(o.order_id) as order_count,sum(o.amount)
from customers c
join orders o
on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
having count(o.order_id) >1;


--Q9. Find customers who never placed an order.
select c.customer_id,c.customer_name 
from customers c
left join  orders o 
on c.customer_id=o.customer_id
where o.order_id is null;



--Q10. Find the average order value for each customer.
select c.customer_id, c.customer_name,round(avg (o.amount),2) as avg_value
from customers c 
join orders o 
on c.customer_id=o.customer_id
group by  c.customer_id, c.customer_name


##Employee Analysis
--Q11. Find the total sales handled by each employee and display their employee name.
select e.employee_id,e.employee_name,sum(o.amount) as sales_amount
from employees e
join orders o 
on e.employee_id=o.employee_id
group by e.employee_id,e.employee_name

--Q12. Find the highest-performing employee in terms of total sales.
select e.employee_id,e.employee_name,sum(o.amount) as sales_performance
from employees e
join orders o 
on e.employee_id=o.employee_id
group by e.employee_id,e.employee_name
order by sales_performance desc 
limit 1


--Q13. Find employees whose total sales are greater than the average employee sales. 
with employee_sales as (
select e.employee_id,e.employee_name,sum(o.amount) as total_sales
from employees e
join orders o 
on e.employee_id=o.employee_id
group by e.employee_id,e.employee_name
)
select employee_id,employee_name,total_sales from employee_sales 
where total_sales>(select avg(total_sales)from employee_sales)



--Q14. Find the highest-paid employee in each department.
  select e.employee_id,e.employee_name,d.department_name ,e.salary
 from(select *,
 dense_rank()over(partition by department_id order by salary DESC) as highest_salary
 from employees)e 
 join departments d
 on e.department_id=d.department_id
 where highest_salary =1;


--15. Find employees whose sales are above their department's average sales.
with department_sales as (
select e.employee_id,e.employee_name,d.department_id,d.department_name,sum(o.amount)as total_sales
from employees e
join departments d
on e.department_id=d.department_id
join orders o
on e.employee_id=o.employee_id
group by e.employee_id,e.employee_name,d.department_id,d.department_name)
select employee_id,employee_name,department_name,total_sales
from(select * ,avg(total_sales)over(partition by department_id)as department_avg_sales
from department_sales)e
where total_sales>department_avg_sales




##Department & Business Analysis
--16. Find total sales generated by each department.
select d.department_id,d.department_name,sum(o.amount)as sales_generated
from departments d
join employees e
on d.department_id=e.department_id
left join orders o 
on e.employee_id=o.employee_id
group by d.department_id,d.department_name


--17. Find departments contributing more than 20% of total company revenue.
with department_revenue as(
select d.department_id,d.department_name,sum(o.amount)as depart_revenue
from departments d
join employees e
on d.department_id=e.department_id
join orders o 
on e.employee_id=o.employee_id
group by d.department_id,d.department_name
)
select department_id,department_name,depart_revenue
from department_revenue
where depart_revenue>(select sum(depart_revenue)*0.20 from department_revenue)

--18. Find the percentage contribution of each department to total revenue. 
with department_sales as (
select d.department_id,d.department_name,sum(o.amount)as department_revenue
from departments d 
join employees e 
on d.department_id=e.department_id
join orders o 
on e.employee_id=o.employee_id
group by  d.department_id,d.department_name
)
select
department_id,
department_name,
department_revenue,
round(department_revenue*100.0/(select sum(department_revenue) from department_sales),2)as revenue_percent
from department_sales






##Advanced SQL
--Q19. Find the top-selling product in each category.
with product_sales as (
select p.product_id,p.product_name,p.category,sum(o.amount)as total_sales
from products p
join orders o
on p.product_id=o.product_id
group by  p.product_id,p.product_name,p.category
)
select product_id,product_name,category,total_sales
from (select*,
dense_rank()over(partition by (category) order by total_sales desc)as sales_rank
from product_sales)
where sales_rank=1

--20. Find customers contributing to 80% of total revenue.
WITH customer_sales AS (
    SELECT
        c.customer_id,
        c.customer_name,
        SUM(o.amount) AS customer_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY
        c.customer_id,
        c.customer_name
),

cumulative_sales AS (
    SELECT
        customer_id,
        customer_name,
        customer_revenue,
        SUM(customer_revenue) OVER (
            ORDER BY customer_revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_revenue
    FROM customer_sales
)

SELECT
    customer_id,
    customer_name,
    customer_revenue,
    cumulative_revenue,
    ROUND(
        cumulative_revenue * 100.0 /
        (SELECT SUM(customer_revenue) FROM customer_sales),
        2
    ) AS cumulative_percentage
FROM cumulative_sales
WHERE cumulative_revenue <= (
    SELECT SUM(customer_revenue) * 0.80
    FROM customer_sales
)
ORDER BY customer_revenue DESC;





